(define tolerance 0.00001)
(define (cube x) (* x x x))
(define (fixed-point f first-guess)
  (define (close-enough? v1 v2)
    (< (abs (- v1 v2)) tolerance))
  (define (try guess)
    (let ((next (f guess)))
      (if (close-enough? guess next)
          next
          (try next))))
  (try first-guess))
(define (average x y)
  (/ (+ x y) 2))
(define (square x) (* x x))
(define (deriv g)
  (lambda (x)
    (/ (- (g (+ x dx)) (g x)) dx)))
(define dx 0.00001)
(define (newton-transform g)
  (lambda (x)
    (- x (/ (g x) ((deriv g) x)))))
(define (newtons-method g guess)
  (fixed-point (newton-transform g) guess))
(define (cubic a b c);关键部分
  (lambda (x) (+ (cube x) (* (square x) a) (* b x) c)))
(define (cubic-ans a b c)
  (newtons-method (cubic a b c) 1))
(define (run-test)
  (display  (cubic-ans 1 2 3))
  (newline)
  (display (cubic-ans 2 43 43)))
