(define (tree-map pro tree)
  (map (lambda (sub-tree)
         (if (not (pair? sub-tree))
             (pro sub-tree)
             (tree-map pro sub-tree)))
       tree))
(define (square-tree tree)
  (define (square x) (* x x))
  (tree-map square tree))
(define test (list 1
                   (list 2 (list 3 4) 5)
                   (list 6 7)))