;额，卧槽，做着做着忘了原题是什么了
(define nil '())
(define (deal pre? ls result)
    (cond ((null? ls) result)
          ((pre? (car ls))
           (deal pre? (cdr ls) (cons (car ls) result)))
          (else (deal pre? (cdr ls) result))))
(define (pick pre? ls)
  (reverse (deal pre? ls nil)))
(define (same-parity x . y)
  (let ((ls (cons x y)))
    (if (odd? x)
        (pick odd? ls)
        (pick even? ls))))
(same-parity 1 2 3 4 5 6 7)
(same-parity 2 3 4 5 6 7)