(define (product term a next b)
  (if (> a b)
      1
      (* (term a)
         (product term (next a) next b))))
(define (factor b)
  (define (son k)
    (cond ((even? k) (+ k 2))
          (else (+ k 1))))
  (define (mother k)
    (cond ((even? k) (+ k 1))
          (else (+ k 2))))
  (define (term k)
    (/ (son k) (mother k)))
  (define (fa-next k)
    (+ 1 k))
  (product term 1.0 fa-next b))
(define (run-test)
  (display (* 4 (factor 1000)))
  (newline)
  (display (* 4 (factor 10000))))