(define (cube x) (* x x x))
(define (sum term a next b)
  (if (> a b)
      0
      (+ (term a)
         (sum term (next a) next b))))
(define (sip f a b n)
  (define h (/ (- b a) n))
  (define (factor k)
    (cond ((or (= k 0) (= k n) 1))
          ((even? k) 2)
          (else 4)))
  (define (term k)
    (* (factor k)
       (f (+ a (* k h)))))
  (define (next k)
    (+ k 1))
  (* (/ h 3)
     (sum term 0 next b)))
(define (run-test)
  (display (sip cube 0 1.0 100))
  (display (sip cube 0 1.0 1000)))

;;我草，这个版本也有问题