(define (cube x) (* x x x))
(define (sum term a next b)
  (if (> a b)
      0
      (+ (term a)
         (sum term (next a) next b))))
(define (sip f a b n)
  (define h (/ (- b a) n))
  (define (factor k)
    (cond ((or (= k 0) (= k n)) 1)
          ((even? k) 2)
          (else 4)))
  (define (sip-term k)
    (* (factor k)
       (f (+ a (* h k)))))
  (define (sip-next k)
    (+ k 1))
  (* (/ h 3)
     (sum sip-term 0 sip-next n)))
(define (run-test)
  (display (sip cube 0 1.0 100))
  (newline)
  (display (sip cube 0 1.0 1000))
  (display (sip cube 0 1.0 10000000)))
;这个版本应该就对了，思路也清晰。隐约感觉第一个版本不知道什么地方有问题。