(define (make-point x y) (cons x y))
(define (x-point point) (car point))
(define (y-point point) (cdr point))

(define (make-rect a-point b-point)
  (cons a-point b-point))
(define (vert rect)
  (let ((a-p (car rect))
	(b-p (cdr rect)))
    (abs (- (y-point a-p)
	    (y-point b-p)))))
(define (hor rect)
  (let ((a-p (car rect))
	(b-p (cdr rect)))
    (abs (- (x-point a-p)
	    (x-point b-p)))))

(define (cal-circu rect)
  (let ((v (vert rect))
	(h (hor rect)))
    (* 2 (+ v h))))
(define (cal-area rect)
  (let ((v (vert rect))
	(h (hor rect)))
    (* h v)))
